<a href="https://colab.research.google.com/github/tiara070403/skripsi/blob/main/mahasiswa_pencinta_alam1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
#Crawling

twitter_auth_token = 'a239bbabcad63391bd9258a75d8f2b0aaef0a4ab'

In [18]:
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Hit:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Fetched 257 kB in 2s (149 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.20).
gnupg is already the newest version (2.2.27-3ubuntu2.3).
0 upgraded, 0 newly installed, 0 to remove and 38 not upgraded.
gpg: cannot open '/dev/tty': No such device or address
curl: (23) Failed writing body
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (20.19.2-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 38 not upgraded.
v20.19.2

In [20]:
# Crawl Data

filename = 'mahasiswa_pencinta_alam1.csv'
search_keyword = 'mahasiswa pencinta alam since:2017-01-01 until:2018-12-01 lang:id'
limit = 2000

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/mahasiswa_pencinta_alam1.csv, renaming to ./tweets-data/mahasiswa_pencinta_alam1.old.csv

Filling in keywords: mahasiswa pencinta alam since:2017-01-01 until:2018-12-01 lang:id


-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 20


Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 39

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 57


Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 61


Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 74


Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 85


Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 94


Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 97


Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 115

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 131


Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 149


Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 165

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 182


Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 201

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 220

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/mahasiswa_pencinta_alam1.csv
Total tweets saved: 232
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@ee8b1c42d7e23d48468eb1bdc737d4f2"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] TimeoutError: page.click: Timeout 60000ms exceeded.
Call log:
  - waiting for locator('text=Retry')

Keywords: mahasiswa pencinta alam since:2017-01-01 until:2018-12-01 lang:id
Twitter Harvest v 2.6.1

If you need help, please send this error screenshot to the maintainer, it was saved to "/content/tweets-data/Error-03-06-2025_16-13-58.png"
⠙

In [21]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1064545170375540736,Mon Nov 19 15:45:21 +0000 2018,6,Empat orang mahasiswa asal Garut terjatuh di G...,1064545170375540736,https://pbs.twimg.com/ext_tw_video_thumb/10645...,NaN,in,NaN,0,0,2,https://x.com/undefined/status/106454517037554...,3306771829,NaN
1,1063694311685005312,Sat Nov 17 07:24:21 +0000 2018,1,Pelantikan Mapala Brimplas Fakultas Hukum UMPa...,1063694311685005312,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/106369431168500...,2392869806,NaN
2,1063322479177781249,Fri Nov 16 06:46:49 +0000 2018,1,Mahasiswa Pencinta Alam Universitas Gadjah Mas...,1063322479177781249,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/106332247917778...,88352716,NaN
3,1063322452732764161,Fri Nov 16 06:46:42 +0000 2018,2,Mahasiswa Pencinta Alam Universitas Gadjah Mas...,1063322452732764161,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/106332245273276...,20963426,NaN
4,1063322439277375488,Fri Nov 16 06:46:39 +0000 2018,0,Mahasiswa Pencinta Alam Universitas Gadjah Mas...,1063322439277375488,NaN,NaN,in,NaN,0,2,1,https://x.com/undefined/status/106332243927737...,18129942,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,855957942968827904,Sun Apr 23 01:34:11 +0000 2017,0,Kegiatan mahasiswa pencinta alam ini patut dic...,855957942968827904,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/855957942968827904,15943133,NaN
228,853550242050052097,Sun Apr 16 10:06:50 +0000 2017,0,Sebanyak 11 orang anggota Mahasiswa Pencinta A...,853550242050052097,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/853550242050052097,814063036868632576,NaN
229,851469428428603395,Mon Apr 10 16:18:25 +0000 2017,0,Mapagama akan eksplorasi gua di Thailand: Kelo...,851469428428603395,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/851469428428603395,258168084,NaN
230,846394420756852736,Mon Mar 27 16:12:09 +0000 2017,0,Kamu adalah apa yang kamu fikirkan apa yang bi...,846394420756852736,NaN,NaN,in,NaN,0,0,2,https://x.com/undefined/status/846394420756852736,1202585838,NaN
231,844753961706029056,Thu Mar 23 03:33:33 +0000 2017,0,Pencinta Alam Berduka Ratusan Mahasiswa Gerudu...,844753961706029056,NaN,NaN,in,NaN,0,0,1,https://x.com/undefined/status/844753961706029056,3236715224,NaN

In [22]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 232.